version: 3

services:
  jupyter:
    command: /home/glue_user/jupyter/jupyter_start.sh
    environment:
      - DISABLE_SSL=true
      - AWS_PROFILE=default
      - AWS_REGION=us-east-1
      - DATALAKE_FORMATS=hudi,iceberg
    image: public.ecr.aws/aws-glue-libs:glue_libs_4.0.0_image_01
    ports:
      - 4040:4040
      - 18080:18080
      - 8998:8998
      - 8888:8888
    restart: always
    volumes:
      - ~/.aws:/home/glue_user/.aws
      - ~/local_folder:/home/glue_user/workspace/jupyter_workspace
